### ISSUE TITLE
Compilation problem because of box syntax

### ISSUE THREAD

**Issue by fagossa** [farcaller/shiny#11]
Hi there,

I'm new to rust and I'd like to use _shiny_ as a tool to learn the language. However, I'm not able to compile even a simple test. 

When I try to compile my dummy project (_cargo build_) I get this error:

```
   Compiling shiny v0.1.3
error: box expression syntax is experimental; you can call `Box::new` instead. (see issue #27779)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/shiny-0.1.3/src/lib.rs:120:9
    |
120 |         box MacItems { items: items } as Box<MacResult>
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(box_syntax)] to the crate attributes to enable
```

My test code is basically one of your examples:

```
#![feature(box_syntax)]
#![feature(plugin)]
#![plugin(shiny)]

#[cfg(test)]
mod test {
  describe!(
    before_each {
      let awesome = true;
    }

    it "is awesome" {
      assert!(awesome);
    }

    it "injects before_each into all test cases" {
      let still_awesome = awesome;
      assert!(still_awesome);
    }
  )
}
```

and my cargo file is just this:

```
[package]
name = "shiny test"
version = "0.0.1"
authors = ["me"]
license = "MIT / Apache-2.0"

[dependencies]
shiny = "0.1.3"
```

PS:
- cargo 0.13.0-nightly (b931a0f 2016-09-11)
- gcc version 4.9.2 (Debian 4.9.2-10)

Thanks a lot

**Comment by ujh** [comment]
You could try [stainless](https://github.com/reem/stainless) instead. It does more or less the same things but it actually compiles. 😏

**Comment by farcaller** [comment]
Yes, the official way to use shiny is to use stainless :-) shiny was forked while stainless had a period of bad maintenance, but as of now, it supports more features.
