### ISSUE TITLE
Build fails with rustc 1.4.0 nightly

### ISSUE THREAD

**Issue by milgner** [farcaller/shiny#6]
After the stable branch complained about the use of `#![feature(plugin)]`, I built myself Rust 1.4.0 nightly. But I can't get shiny to work. Unfortunately I'm a total Rust noob, too (just want to write nice tests from the start), so it may be that I'm doing something elementary wrong.
Nonetheless, here's the output:

    lib.rs:68:21: 68:29 error: no method named `as_str` found for type `core::result::Result<syntax::ast::Ident, syntax::diagnostic::FatalError>` in the current scope
    lib.rs:76:21: 76:30 error: mismatched types:
     expected `core::result::Result<(syntax::parse::token::InternedString, syntax::ast::StrStyle), syntax::diagnostic::FatalError>`,
        found `(_, _)`
    (expected enum `core::result::Result`,
        found tuple) [E0308]
    lib.rs:76:21: 76:30 help: run `rustc --explain E0308` to see a detailed explanation
    lib.rs:78:35: 78:51 error: the type of this value must be known in this context
    lib.rs:84:28: 84:38 error: no method named `as_slice` found for type `collections::string::String` in the current scope
    lib.rs:93:21: 93:34 error: the type of this value must be known in this context
    note: in expansion of for loop expansion
    lib.rs:91:5: 121:6 note: expansion site
    lib.rs:95:48: 95:60 error: attempted access of field `stmts` on type `&core::result::Result<syntax::ptr::P<syntax::ast::Block>, syntax::diagnostic::FatalError>`, but no field with that name was found
    note: in expansion of for loop expansion
    lib.rs:91:5: 121:6 note: expansion site
    lib.rs:97:28: 97:33 error: binary operation `+` cannot be applied to type `collections::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::Stmt_>>>` [E0369]
    note: in expansion of for loop expansion
    lib.rs:91:5: 121:6 note: expansion site
    lib.rs:97:28: 97:33 help: run `rustc --explain E0369` to see a detailed explanation
    lib.rs:97:36: 97:48 error: attempted access of field `stmts` on type `&core::result::Result<syntax::ptr::P<syntax::ast::Block>, syntax::diagnostic::FatalError>`, but no field with that name was found
    note: in expansion of for loop expansion
    lib.rs:91:5: 121:6 note: expansion site
    lib.rs:108:32: 108:54 error: the type of this value must be known in this context
    note: in expansion of for loop expansion
    lib.rs:91:5: 121:6 note: expansion site
    lib.rs:111:19: 116:22 error: this function takes 6 parameters but 5 parameters were supplied [E0061]
    lib.rs:111             node: ast::ItemFn(
    lib.rs:112                 cx.fn_decl(Vec::new(), cx.ty(DUMMY_SP, ast::Ty_::TyTup(Vec::new()))),
    lib.rs:113                 ast::Unsafety::Normal,
    lib.rs:114                 abi::Rust,
    lib.rs:115                 empty_generics(),
    lib.rs:116                 body),
    note: in expansion of for loop expansion

**Comment by ujh** [comment]
I've opened #7 with a fix. But I'm not 100% sure that it still works. I just made it compile again.
